import os
import sys
import google.generativeai as genai
from github import Github
import re

def get_file_path_from_issue(issue_body):
    match = re.search(r"File to Modify: `(.*?)`", issue_body)
    if match:
        return match.group(1)
    return None

# Get credentials and context from environment
gemini_api_key = os.getenv("GEMINI_API_KEY")
github_token = os.getenv("GITHUB_TOKEN")
repo_name = os.getenv("GITHUB_REPOSITORY")
issue_number = int(os.getenv("ISSUE_NUMBER"))

# Authenticate
genai.configure(api_key=gemini_api_key)
g = Github(github_token)

# Get repository and issue
repo = g.get_repo(repo_name)
issue = repo.get_issue(number=issue_number)

# --- AI Task --- #

# 1. Determine the file to modify
file_path = get_file_path_from_issue(issue.body)
if not file_path:
    print("Could not determine the file to modify from the issue body.")
    print("Please specify the file in the format: `File to Modify: <path_to_file>`")
    sys.exit()

# 2. Get the file content
file_content = repo.get_contents(file_path).decoded_content.decode()

# 3. Generate the new content
model = genai.GenerativeModel('gemini-pro')
prompt = f"'""Here is the content of the file `{file_path}`:

```
{file_content}
```

Please apply the following changes as described in the issue: '{issue.title}' - '{issue.body}'.

Your response should ONLY be the complete, updated code for the file `{file_path}`. Do not include any other text, markdown, or explanations.
"'""

response = model.generate_content(prompt)
new_content = response.text

# --- Git Operations --- #

# 4. Create a new branch
new_branch_name = f"ai-changes-{issue.number}"
source_branch = repo.get_branch("main")
repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=source_branch.commit.sha)

# 5. Commit the change
repo.update_file(
    path=file_path,
    message=f"feat: Apply AI changes for issue #{issue.number}",
    content=new_content,
    branch=new_branch_name,
    sha=repo.get_contents(file_path).sha
)

# 6. Create a Pull Request
repo.create_pull(
    title=f"AI-Generated Fix for: {issue.title}",
    body=f"This pull request was automatically generated by an AI agent in response to issue #{issue.number}.\n\nPlease review the changes before merging.",
    head=new_branch_name,
    base="main"
)

print(f"Successfully created a pull request for issue #{issue.number}")
