import os
import sys
import google.generativeai as genai
from github import Github, GithubException
import re

def get_file_path_from_issue(issue_body):
    match = re.search(r"`([^`]+)`", issue_body)
    if match:
        return match.group(1)
    return None

def main():
    # --- Get credentials and context --- #
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    github_token = os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY")
    issue_number = int(os.getenv("ISSUE_NUMBER"))

    if not all([gemini_api_key, github_token, repo_name, issue_number]):
        print("Error: Missing one or more required environment variables.")
        sys.exit(1)

    # --- Authenticate & Get Repo/Issue --- #
    genai.configure(api_key=gemini_api_key)
    g = Github(github_token)
    try:
        repo = g.get_repo(repo_name)
        issue = repo.get_issue(number=issue_number)
    except GithubException as e:
        print(f"Error accessing GitHub: {e}")
        sys.exit(1)

    # --- AI Task (Generate new content) --- #
    file_path = get_file_path_from_issue(issue.body)
    if not file_path:
        issue.create_comment("Could not determine the file to modify from the issue body. Please specify the file in the format: `path/to/your/file.ext`")
        sys.exit(1)

    try:
        file_content_obj = repo.get_contents(file_path)
        file_content = file_content_obj.decoded_content.decode()
    except GithubException:
        issue.create_comment(f"Error: The file `{file_path}` could not be found in the repository.")
        sys.exit(1)

    model = genai.GenerativeModel('gemini-pro')
    prompt = f"""Here is the content of the file `{file_path}`:

```
{file_content}
```

Please apply the following changes as described in the issue: '{issue.title}' - '{issue.body}'.

Your response should ONLY be the complete, updated code for the file `{file_path}`. Do not include any other text, markdown, or explanations.
"""

    try:
        response = model.generate_content(prompt)
        new_content = response.text
    except Exception as e:
        issue.create_comment(f"Error generating code with the AI model: {e}")
        sys.exit(1)

    # --- Git Operations --- #
    new_branch_name = f"ai-changes-{issue.number}"
    source_branch_name = "main"

    try:
        source_branch = repo.get_branch(source_branch_name)

        # Delete the branch if it already exists to ensure a clean slate
        try:
            ref = repo.get_git_ref(f"heads/{new_branch_name}")
            print(f"Branch '{new_branch_name}' already exists. Deleting it.")
            ref.delete()
        except GithubException:
            # Branch doesn't exist, which is fine.
            print(f"Branch '{new_branch_name}' does not exist. Proceeding to create.")
            pass

        # Create a new branch from the source branch
        print(f"Creating branch '{new_branch_name}' from '{source_branch_name}'.")
        repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=source_branch.commit.sha)

        # Commit the changes to the new branch
        print(f"Committing changes to file '{file_path}' on branch '{new_branch_name}'.")
        repo.update_file(
            path=file_path,
            message=f"feat: Apply AI changes for issue #{issue.number}",
            content=new_content,
            branch=new_branch_name,
            sha=file_content_obj.sha # SHA of the file on the source branch
        )

        # Create a Pull Request
        print(f"Creating a pull request for branch '{new_branch_name}'.")
        pr = repo.create_pull(
            title=f"AI-Generated Fix for: {issue.title}",
            body=f"This pull request was automatically generated by an AI agent in response to issue #{issue.number}.\n\nPlease review the changes before merging.",
            head=new_branch_name,
            base=source_branch_name
        )

        print(f"Successfully created a pull request for issue #{issue.number}.")
        issue.create_comment(f"I have created a pull request with the requested changes. Please review and merge it. You can find the pull request [here]({pr.html_url}).")

    except GithubException as e:
        error_message = f"An error occurred during the Git operations: {e.data.get('message', str(e))}"
        print(error_message)
        issue.create_comment(error_message)
        sys.exit(1)
    except Exception as e:
        error_message = f"An unexpected error occurred: {str(e)}"
        print(error_message)
        issue.create_comment(error_message)
        sys.exit(1)

if __name__ == "__main__":
    main()
